### ISSUE TITLE
No method error in `BusStopsController#update`

### ISSUE THREAD

**Issue by werebus** [umts/stop-project#154]
```
A NameError occurred in bus_stops#update:

  undefined local variable or method `bus_stop_route' for #<BusStopsController:0x00007fe7f45320a8>
Did you mean?  bus_stop_url
               bus_stop_path
  app/controllers/bus_stops_controller.rb:91:in `update'
```

https://github.com/umts/stop-project/blob/61aa7bb2eefb6768d77da3556503ebc6db93caee/app/controllers/bus_stops_controller.rb#L91

Indeed, `bus_stop_route` isn't a thing in this context. This was introduced in fa9d1bf316e5022f424ded0032df6336e63729f9 So, the feature implemented in #117 never, um, actually worked.

Probably that should be `id: next_stop.hastus_id`.

**Comment by dfaulken** [comment]
That's correct. This is a relatively low-hanging fruit as all that is needed is to implement this change and prove it out with a unit test.
